### ISSUE TITLE
Time into string error

### ISSUE THREAD

**Issue by gavinwye** [controlgroup/CSV-GitHub-import-export#6]
Hi I've been trying to get the CSV export to work but everytime I run that app using

```ruby ./github_issues_to_csv.rb```

I get the following error

```./github_issues_to_csv.rb:130:in `parse': no implicit conversion of Time into String (TypeError)```
	```from ./github_issues_to_csv.rb:130:in `block in <main>'```
	```from ./github_issues_to_csv.rb:103:in `each'```
	```from ./github_issues_to_csv.rb:103:in `<main>'```

Any ideas what's going wrong I don't really know what I'm doing with ruby so it may be something very simple :(

**Comment by gwikle** [comment]
Thanks @quilicicf.  Your workaround saved me a bunch of time.
+1 vote to fix this bug.

**Comment by DanMeltz** [comment]
Merged @gavinwye 's fix.

**Comment by gavinwye** [comment]
@DanMeltz thanks for merging that fix. I'm just about to test it but... i'm being a complete dummy and can't remember how to run the script. Could you help please?

I'm trying the following
1. synch the repo in the github client
2. right click > open in terminal
3. `ruby ./github_issues_to_csv.rb`

which results in the following

`ruby: No such file or directory -- github_issues_to_csv.rb (LoadError)`

What am I doing wrong?

**Comment by gavinwye** [comment]
My previous comment is wrong. I've resolved the issues I was having.

For the future incase anyone is having problems you need to run ```./github_issues_to_csv.rb``` at the ```$``` prompt in terminal. You should then be prompted for your github username, password, organisation, repo, the name of the file and then the milestone you want to export (which can be left blank for all)

This is now working as expected so I'll close the issue 

thanks @DanMeltz for the fix
